### ISSUE TITLE
I Think U can Try Something Else

### ISSUE THREAD

**Issue by Pspfriends** [pspfriends1/SampleC#3]
Try to make use of that input String in ur project

[Just Checkout this code](https://www.programiz.com/c-programming/examples)

**Hope U can See Through this one**

**Comment by pspfriends1** [comment]
I think This Fixes the issue #3

**Comment by pspfriends1** [comment]
Hey What Else u recommend for this

**Comment by pspfriends1** [comment]
I hope u don't have any other twist in this 

82ed74e1b40fce23b4911c9aa7d9cd4b538460b5

**Comment by pspfriends1** [comment]
This fixes #3

**Comment by Pspfriends** [comment]
ya i think so
